name: Release

on: [push, pull_request]

jobs:
  CSharpMath:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.401'      
  
    - name: Build GitHub Releases draft artifacts
      run: |
        # .NET Core MSBuild cannot parse , and ; correctly so we replace them with substitutions: https://github.com/dotnet/msbuild/issues/471#issuecomment-366268743
        # https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion
        # ${parameter/pattern/string} If pattern begins with ‘/’, all matches of pattern are replaced with string. Normally only the first match is replaced.
        RELEASE_NOTES=${RELEASE_NOTES//,/%2C}
        RELEASE_NOTES=${RELEASE_NOTES//;/%3B}
        
        # -r for restore
        dotnet msbuild -r -p:Configuration=Release -p:PackageVersion="42.$GITHUB_RUN_NUMBER-playingwithphysics" CSharpMath.CrossPlatform.slnf

    - name: dotnet publish
      run: dotnet nuget push --api-key ${{ secrets.MyGet }} --source https://www.myget.org/F/playingwithphysics/api/v2/package .nupkgs/**/*.nupkg 
  
    - name: Archive nugets
      uses: actions/upload-artifact@v3
      with:
        name: nugets
        path: .nupkgs/*